### ISSUE TITLE
チャリスポット やること

### ISSUE THREAD

**Issue by shari5790** [s-hirata0831/meBike2024Soft#2]
・ラズパイを用いたME-bike管理システムの作成
・NFCタグを用いた施錠システムの作成
・ソレノイドロックを用いた自転車のロック機構
・ラズパイ、NFCタグをしまう箱の作成

<時間があれば>
・スタンドの作成
・電気問題

**Comment by shari5790** [comment]
課題更新
・ソレノイドロックと自転車を繋げる方法を考える。
・ラズパイを用いたME-bike管理システムの作成
・ソレノイドロックを用いた自転車のロック機構
・ラズパイ、NFCタグをしまう箱の作成

<時間があれば>
・スタンドの作成
・電気問題
・スマホからラズパイを通してロックを制御

**Comment by s-hirata0831** [comment]
完成しました。
